version: '3.8'

services:
  db:
    container_name: parkit_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - data_parkit_db:/var/lib/postgresql/data
volumes:
  data_parkit_db: